DST_FOLDER_SAVE_RESULTS: ... # TO FILL
WANDB_ITERATOR: 0 
WANDB_ENTITY: ... # TO FILL
DTYPE: float32
BUFFER_SIZE: 1024
LOW_RESOLUTION_SHAPE:
- 128
- 128
- 3
HIGH_RESOLUTION_SHAPE:
- 512
- 512
- 3
SCALE_FACTOR: 4
EPOCHS: 1
SAVE_VAL_PERIOD: 1
BATCH_SIZE: 2
STEPS_PER_EPOCH: 1
LABEL_NOISE: true
VAL_BATCH_SIZE: 2
MODEL:
  DISCRIMINATOR:
    N_BLOCKS: 7
    N_FILTERS_START: 64
  GENERATOR:
    L_FILTERS:
    - 64
    - 64
    - 64
    - 64
    - 64
